packages:
  - name: telegram
    environment:
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      TELEGRAM_BOT_HOOK_PATH: "${TELEGRAM_BOT_HOOK_PATH}"
    actions:
      - name: bot 
        runtime: nodejs:default